name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright Browsers (chỉ cài browser nếu chưa có)
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Set environment variable for BASE_URL
      - name: Set environment variable for BASE_URL
        run: echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV

      # Ensure server is up and running
      - name: Ensure server is up and running
        run: |
          curl --fail ${{ secrets.BASE_URL }} || exit 1

      # Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test

      # Upload report
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
