name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      # Cài đặt Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Cài đặt các phụ thuộc
      - name: Install dependencies
        run: npm ci

      # Cài đặt Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Cài đặt biến môi trường BASE_URL từ Secrets
      - name: Set environment variable for BASE_URL
        run: echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV

      # Kiểm tra server trước khi chạy test (kiểm tra BASE_URL)
      - name: Ensure server is up and running
        run: |
          curl --fail ${{ secrets.BASE_URL }} || exit 1

      # Chạy các test Playwright
      - name: Run Playwright tests
        run: npx playwright test

      # Lưu lại báo cáo
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
